apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: contract-golden-image-on-push
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-appstudio/ec-golden-image:latest
    - name: dockerfile
      value: ./Containerfile
    - name: path-context
      value: .
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:devel@sha256:914683ecb16e5761b08d9ac17ee4c99f5d2d91dcd323e565a3f066c4a25fd591
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
