---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: contract-golden-image-on-tag-latest
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
spec:
  params:
    - name: revision
      value: '{{revision}}'
  pipelineSpec:
    params:
      - name: revision
    tasks:
      - name: tag-with-latest
        params:
          - name: revision
            value: '$(params.revision)'
        taskSpec:
          params:
            - name: revision
          steps:
            - name: tag-with-latest
              image: registry.access.redhat.com/ubi9/skopeo:latest@sha256:0f0e1d8607f5f290d1dc5ddb62744bb11647ff465898b2a3bfb1653c86ae2214
              script: |
                #!/usr/bin/env bash
                SRC_REF=quay.io/redhat-appstudio/ec-golden-image:$(params.revision)
                TARGET_REF=quay.io/redhat-appstudio/ec-golden-image:latest

                retries=0
                while ! skopeo inspect docker://${SRC_REF} >/dev/null 2>&1; do
                  (( retries++ ))
                  if (( retries > 200 )); then
                    echo
                    echo ${SRC_REF} has not been pushed within 10 min
                    exit 1
                  fi
                  echo -n .
                  sleep 3
                done
                echo
                echo ${SRC_REF} has been pushed, copying to ${TARGET_REF}

                skopeo copy docker://${SRC_REF} docker://${TARGET_REF}
